apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: stackrox-pipeline-prevail-2021
spec:
  resources:
    - name: git-source
      type: git
    - name: base-image
      type: image  
    - name: app-image
      type: image
  params:
    - default: 'https://github.com/kitty-catt/customer-ms-spring'
      description: A git repo that contains a java application that is build using maven.
      name: git-url
      type: string    
    - default: 'solo'
      description: The revision to pull and build.
      name: git-revision
      type: string
    - default: 'app-repo-dir'
      description: the folder where the application repo will be checked out
      name: git-repo-checkout-dir
      type: string   
    - default: '.'
      description: the directory containing the pom
      name: pom-dir
      type: string               
    - default: 'customer-ms-spring'
      description: The name of the service to pull and build.
      name: app-name
      type: string   
    - default: 'customer-ms-spring'
      description: The name of the service to deploy.
      name: deployment
      type: string    
    - default: 'full-bc'
      description: The namespace where the deployment is updated.
      name: dev-namespace
      type: string    
    - default: 'jmeter-testplan/blue-compute-shop.jmx'
      description: the path to the jmeter test plan in the repo
      name: test-plan
      type: string
    - default: 'jmeter-testplan/order-a-calculator.jmx'
      description: the path to the jmeter test plan in the repo
      name: functional-test-plan
      type: string      
    - default: '3'
      description: the number of jmeter threads that will execute the testplan
      name: jmeter-users
      type: string
    - default: '50'
      description: the number of times that an individual thread will execute the testplan
      name: jmeter-loop-count
      type: string        
  tasks:
    - name: rescan-base-img
      taskRef:
        kind: Task
        name: aot-stackrox-scan
      params:
        - name: image-namespace
          value: "tools-images"
        - name: image-name
          value: "ubi"          
      resources:
        inputs:
        - name: image
          resource: base-image 
    - name: clone-1
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)           
        - name: subdirectory
          value: $(params.git-repo-checkout-dir)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: src-workspace-01
    - name: artifact-build
      params:
        - name: GOALS
          value:
            - clean
            - package
            - deploy
        - name: PROXY_PROTOCOL
          value: http
        - name: module
          value: $(params.app-name)
        - name: pom-dir
          value: $(params.pom-dir) 
        - name: git-repo-checkout-dir
          value: $(params.git-repo-checkout-dir)                  
      taskRef:
        kind: Task
        name: aot-maven
      runAfter:
        - clone-1        
      workspaces:
        - name: maven-settings
          workspace: maven-settings      
        - name: source
          workspace: src-workspace-01
        - name: maven-repo
          workspace: local-maven-repo  
    - name: sonar-scan
      params:
      - name: app-name
        value: $(params.app-name)   
      - name: git-repo-checkout-dir
        value: $(params.git-repo-checkout-dir)                    
      taskRef:
        kind: Task      
        name: aot-sonar-java
      runAfter: 
        - artifact-build   
      workspaces:
        - name: source
          workspace: src-workspace-01                 
    - name: img-build
      taskRef:
        kind: Task
        name: aot-buildah
      resources:
        inputs:
        - name: source
          resource: git-source
        outputs:
        - name: image
          resource: app-image
      params:
      - name: TLSVERIFY
        value: "false"
      - name: CONTEXT
        value: $(params.pom-dir)        
      runAfter: 
      - dep-track
      - sonar-scan  
      - rescan-base-img         
    - name: clone-2
      taskRef:
        name: aot-mockup         
    - name: dep-check
      taskRef:
        name: aot-mockup
      runAfter: 
        - clone-2  
    - name: dep-track
      taskRef:
        name: aot-mockup
      runAfter: 
      - dep-check               
    - name: scan-app-img
      taskRef:
        kind: Task
        name: aot-stackrox-scan
      resources:
        inputs:
        - name: image
          resource: app-image 
      params:
        - name: image-namespace
          value: "pipelines"
        - name: image-name
          value: $(params.app-name)                   
      runAfter: 
      - img-build                      
    - name: roll-out
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash

            echo "updating deployment: $(params.deployment)"
            echo "in namespace: $(params.dev-namespace)"

            # The Golden Guidance:
            oc tag pipelines/$(params.app-name):latest $(params.dev-namespace)/$(params.app-name):latest

            oc set image deployment $(params.deployment) $(params.deployment)=$(params.app-name):latest -n $(params.dev-namespace)

            # How do we know that the image was rolled out?
            echo "sleep for 180 seconds"
            sleep 180

            echo "done"            

        - name: ARGS
          value:
            - ""
      resources:
        inputs:
          - name: source
            resource: git-source
      taskRef:
        kind: ClusterTask
        name: openshift-client 
      runAfter: 
      - scan-app-img
    - name: functional-test
      taskRef:
        name: aot-mockup
      runAfter: 
      - roll-out
    - name: performance-test
      taskRef:
        name: aot-mockup
      runAfter: 
      - functional-test
  workspaces:
    - name: maven-settings
    - name: src-workspace-01
    - name: src-workspace-02    
    - name: local-maven-repo   
    - name: local-sonar-repo
    - name: local-owasp-repo     
    - name: images-url
    - name: report