apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: customer-image-internal
  spec:
    params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/pipelines/customer-ms-spring
    type: image
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: customer-image-external
  spec:
    params:
    - name: url
      value: quay.io/kitty_catt/customer-ms-spring
    type: image    
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: customer-source-tomcat-root
  spec:
    params:
    - name: revision
      value: tomcat-fixed-runs-root
    - name: url
      value: https://github.com/kitty-catt/customer-ms-spring
    type: git
kind: List
