apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: auth-pipeline-liberty-internal-
spec:
  serviceAccountName: appsody-sa
  timeout: "1h0m0s"  
  pipelineRef:
    name: build-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: auth-ms-liberty-source
    - name: docker-image
      resourceRef:
        name: auth-ms-liberty-image-internal